CREATE TABLE TBL_FCT_PROPERTIES (
  PROPERTIE_ID INT,
  STATE VARCHAR(50),
  CITY VARCHAR(60),
  COLONY VARCHAR(70),
  STREET VARCHAR(120),
  EXTERNAL_NUM VARCHAR(30),
  USER_ID INT,
  TYPE VARCHAR(20),
  PURPOSE VARCHAR(10),
  PRICE INT
)
